# Generated by Django 2.2.4 on 2019-08-18 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('mod_user_id', models.IntegerField(default=1, editable=False, verbose_name='更新ユーザーID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='内容')),
                ('detail', models.CharField(default='', max_length=300, verbose_name='内容')),
            ],
        ),
    ]
